---
name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: visual-studio-marketplace
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g tfx-cli
      - run: wget -O "${GITHUB_WORKSPACE}/extension.vsix" ${{ github.event.release.assets_url }}/FrontierDigital.Ranger-${{ github.event.release.tag_name }}.vsix
      - run: |
          npx tfx-cli extension publish \
            --vsix "${GITHUB_WORKSPACE}/extension.vsix" \
            --service-url https://marketplace.visualstudio.com \
            --token "${{ secrets.VISUAL_STUDIO_MARKETPLACE_TOKEN }}" \
            --share-with "${{ secrets.VISUAL_STUDIO_MARKETPLACE_PUBLISHER }}"
